### ISSUE TITLE
Keep getting error:{"code":"sherpaBadRequest","message":"content-type of request should be application/json"}

### ISSUE THREAD

**Issue by johan974** [mjl-/sherpa-website#1]
Can you please have a look at this Java code - using OkHttp requesting a service? 

MediaType JsonType = MediaType.parse("application/json");
OkHttpClient client = new OkHttpClient();
String jsonBody = "{\"params\":[\"wandelnet\"," + id + "]}";
RequestBody body = RequestBody.create(jsonBody, JsonType); // new
Request request = new Request.Builder()
        .url( "https://wandelnet.api.routemaker.nl/routemaker/getPublishedRoute")
        .post(body)
        .addHeader("Content-Type", "application/json; charset=utf-8")
        .addHeader( "Accept", "application/json")
        .build();
Response response = client.newCall(request).execute();

**Comment by mjl-** [comment]
This looks like a problem with the routemaker API implementation in that it does not understand the charset=utf-8 attribute in the Content-Type header.
Could you give it a try with just "application/json" as Content-Type?

To illustrate, this first command works, I'm getting the JSON route back:

    curl 'https://wandelnet.api.routemaker.nl/routemaker/getPublishedRoute' -X POST -H 'Content-Type: application/json' --data-raw '{"params":["wandelnet",587]}'

This second command results in the error you are seeing:

    curl 'https://wandelnet.api.routemaker.nl/routemaker/getPublishedRoute' -X POST -H 'Content-Type: application/json; charset=utf-8' --data-raw '{"params":["wandelnet",587]}'
    # {"result":null,"error":{"code":"sherpaBadRequest","message":"content-type of request should be application/json"}}

**Comment by johan974** [comment]
Also with "Content-Type: application-json" the above error is shown.

**Comment by mjl-** [comment]
You could try removing the explicit call to addHeader with Content-Type, okhttpclient may also be adding one.
What is often also helpful is to just start a local tcp listener (e.g. nc -l 8000) and let okhttpclient do an http call to localhost:8000. You'll see exactly what it is sending.

**Comment by mjl-** [comment]
Also, I'm assuming you tried "Content-Type: application/json" instead of the mentioned "Content-Type: application-json". (:

**Comment by johan974** [comment]
Client request issue: 

This solved the issue: 
RequestBody body = RequestBody.create(jsonBody.getBytes(“UTF-8”), JsonType);
OkHttp automatically adds a charset when it does string encoding, and we need to prevent this here.
